export const EVENTS = {
  FRIEND_REQUEST: {
    CREATED: 'FRIEND_REQUEST_CREATED',
    UPDATED: 'FRIEND_REQUEST_UPDATED',
    ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
    REJECTED: 'FRIEND_REQUEST_REJECTED',
  },
} as const;
